"""PeerSync by Nickston portable Windows shell entrypoint (Python/Tk).

Modes:
  (default)      GUI: tray + window + live Core.
  --smoke        M0 gate: single instance, DPAPI identity, core install to a
                 stable path, spawn Core, framed IPC handshake + ping, status,
                 graceful exit. Prints "M0 SMOKE PASS" and exits 0 on success.
"""

import os

from runtime.compat import UPDATE_MANIFEST_SCHEMAS
import sys
import time
import threading

# make the local package layout importable both from source and frozen build
HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

from windows import dpapi, paths, single_instance  # noqa: E402
from runtime import core_installer  # noqa: E402
from ipc.core_client import CoreClient  # noqa: E402
from diagnostics import DiagnosticsEndpoint, DiagnosticsRecorder  # noqa: E402

APP_VERSION = "0.0.0"
_SMOKE_LOG = None
_FAULT_LOG_HANDLE = None
_PROCESS_STARTED_EPOCH = time.time()
_UPDATE_SOURCE_CACHE = None
_DEBUG_ENABLED = False
_DIAGNOSTICS = None
_DIAGNOSTIC_ENDPOINT = None
CORE_RESTART_MAX_ATTEMPTS = 5
CORE_RESTART_BASE_DELAY = 0.5


def _p(*parts):
    line = " ".join(str(p) for p in parts)
    print(line, flush=True)
    if _DIAGNOSTICS is not None:
        _DIAGNOSTICS.log("debug", "shell", "cli", "stdout", line)
    if _SMOKE_LOG:
        try:
            with open(_SMOKE_LOG, "a", encoding="utf-8") as fh:
                fh.write(line + "\n")
        except OSError:
            pass


def _smoke_metric(**updates):
    """Atomically publish machine-readable startup milestones for artifact-smoke."""
    if not _SMOKE_LOG:
        return
    import json

    path = os.path.join(paths.logs_dir(), "smoke-metrics.json")
    data = {}
    try:
        if os.path.isfile(path):
            with open(path, encoding="utf-8") as fh:
                data = json.load(fh)
    except (OSError, ValueError):
        data = {}
    data.update(updates)
    tmp = path + ".tmp"
    payload = json.dumps(data, sort_keys=True)
    # Windows can deny os.replace while artifact-smoke (or Defender) has the
    # previous metrics file open. Retry; do not drop the last smokePass write.
    for attempt in range(12):
        try:
            with open(tmp, "w", encoding="utf-8") as fh:
                fh.write(payload)
                fh.flush()
                try:
                    os.fsync(fh.fileno())
                except OSError:
                    pass
            os.replace(tmp, path)
            return
        except OSError as err:
            if attempt == 11:
                _p("note: smoke-metrics write failed:", err)
            else:
                time.sleep(0.05)
    try:
        os.remove(tmp)
    except OSError:
        pass



def _enable_fault_log():
    """Keep a native/Python crash traceback for windowed frozen builds."""
    global _FAULT_LOG_HANDLE
    if _FAULT_LOG_HANDLE is not None:
        return
    try:
        import faulthandler

        os.makedirs(paths.logs_dir(), exist_ok=True)
        fault_path = os.path.join(paths.logs_dir(), "python-fault.log")
        paths.rotate_log_files(fault_path)
        _FAULT_LOG_HANDLE = open(fault_path, "ab", buffering=0)
        faulthandler.enable(file=_FAULT_LOG_HANDLE, all_threads=True)
    except Exception:  # diagnostics must never block startup
        _FAULT_LOG_HANDLE = None


def build_label():
    try:
        import build_info  # generated by the build script

        return getattr(build_info, "BUILD_LABEL", "dev")
    except Exception:  # noqa: BLE001 - dev fallback
        return os.environ.get("PEERSYNC_BUILD", "dev")


def app_version():
    try:
        import build_info

        return getattr(build_info, "APP_VERSION", APP_VERSION)
    except Exception:  # noqa: BLE001
        return APP_VERSION


def release_version():
    """Public PeerSync version: DDMMYY only."""
    try:
        import build_info

        return str(getattr(build_info, "RELEASE_VERSION", build_label()) or build_label())
    except Exception:  # noqa: BLE001
        return build_label()


def release_revision():
    """Monotonic within-day release revision compiled into this launcher.

    The UI keeps showing the date-only DDMMYY label. The revision is the
    machine-orderable identity that makes two different official builds of the
    same calendar date distinguishable to update ordering.
    """
    from runtime.updater import parse_release_revision

    value = 0
    try:
        import build_info

        value = getattr(build_info, "RELEASE_REVISION", 0)
    except Exception:  # noqa: BLE001 - dev fallback
        value = os.environ.get("PEERSYNC_RELEASE_REVISION", 0)
    return parse_release_revision(value)


def update_signing_public_key():
    """Pinned Ed25519 public key for release verification (hex, 32 bytes)."""
    value = ""
    try:
        import build_info

        value = str(getattr(build_info, "UPDATE_SIGNING_PUBLIC_KEY", "") or "").strip().lower()
    except Exception:  # noqa: BLE001
        pass
    # Source/dev runs may inject a key. Frozen releases trust only the value
    # compiled into build_info.py.
    if not value and not getattr(sys, "frozen", False):
        value = str(os.environ.get("PEERSYNC_UPDATE_SIGNING_PUBLIC_KEY") or "").strip().lower()
    if len(value) == 64 and all(ch in "0123456789abcdef" for ch in value):
        return value
    return ""


def allow_unsigned_update():
    """Return whether remembered-device P2P executable updates may be unsigned.

    This fork intentionally allows unsigned launcher distribution. Transport
    integrity is still enforced by size + SHA-256 and update serving/receiving
    remains restricted to remembered devices marked locally as ``mine``.
    """
    try:
        import build_info

        return bool(getattr(build_info, "ALLOW_UNSIGNED_UPDATE", True))
    except Exception:  # noqa: BLE001 - dev fallback
        value = str(os.environ.get("PEERSYNC_ALLOW_UNSIGNED_UPDATE", "1") or "1").strip().lower()
        return value not in ("0", "false", "no", "off")


def _update_platform():
    if os.name != "nt":
        return "unsupported"
    import platform

    machine = str(platform.machine() or "").lower()
    if machine in ("amd64", "x86_64"):
        return "win-x64"
    if machine in ("arm64", "aarch64"):
        return "win-arm64"
    return "win-" + (machine or "unknown")


def _manifest_revision_matches(manifest):
    """A sidecar must describe this launcher's own release revision.

    A sidecar without a revision predates the monotonic revision identity and
    still matches, because the revision is not part of the signed payload.
    """
    from runtime.updater import parse_release_revision

    if "releaseRevision" not in manifest:
        return True
    return parse_release_revision(manifest.get("releaseRevision")) == release_revision()


def update_source_payload():
    """Describe the frozen launcher under the configured update trust policy.

    Unsigned mode permits remembered-mine distribution without a sidecar.
    SHA-256 verifies integrity, not publisher authentication.
    """
    global _UPDATE_SOURCE_CACHE
    if _UPDATE_SOURCE_CACHE is not None:
        return dict(_UPDATE_SOURCE_CACHE)

    payload = {
        "available": False,
        "path": None,
        "platform": _update_platform(),
        "size": 0,
        "sha256": "",
        "signature": None,
        "releaseRevision": release_revision(),
    }
    if getattr(sys, "frozen", False) and os.name == "nt":
        exe = os.path.abspath(sys.executable)
        try:
            import json
            from runtime.updater import comparable_app_version, sha256_file

            digest, size = sha256_file(exe)
            signature = None
            key = update_signing_public_key()

            # A valid signed sidecar is used when present, but it is optional
            # in unsigned mode. Never advertise sidecar metadata unless it
            # matches the exact executable bytes being served.
            if key:
                try:
                    manifest_path = exe + ".update.json"
                    with open(manifest_path, encoding="utf-8") as fh:
                        manifest = json.load(fh)
                    expected_version = comparable_app_version(app_version(), build_label())
                    valid = (
                        isinstance(manifest, dict)
                        and manifest.get("schema") in UPDATE_MANIFEST_SCHEMAS
                        and str(manifest.get("appVersion") or "") == expected_version
                        and str(manifest.get("buildLabel") or "") == build_label()
                        and _manifest_revision_matches(manifest)
                        and str(manifest.get("platform") or "") == payload["platform"]
                        and int(manifest.get("size") or 0) == size
                        and str(manifest.get("sha256") or "").lower() == digest.lower()
                        and isinstance(manifest.get("signature"), str)
                        and len(manifest.get("signature")) == 128
                        and str(manifest.get("publicKey") or "").lower() == key
                    )
                    if valid:
                        signature = str(manifest["signature"]).lower()
                except (OSError, ValueError, TypeError):
                    signature = None

            if allow_unsigned_update() or signature:
                payload.update(
                    {
                        "available": True,
                        "path": exe,
                        "size": size,
                        "sha256": digest,
                        "signature": signature,
                    }
                )
        except (OSError, ValueError, TypeError):
            pass
    _UPDATE_SOURCE_CACHE = dict(payload)
    return payload


def hello_payload(seed):
    return {
        "shellProtocol": 1,
        "identitySeedHex": seed,
        "deviceName": str(os.environ.get("COMPUTERNAME") or "PeerSync")[:255],
        "deviceType": "desktop",
        "dataRoot": paths.data_root(),
        "appVersion": app_version(),
        "buildLabel": build_label(),
        "releaseRevision": release_revision(),
        "updateSource": update_source_payload(),
        "updateTrust": {"publicKeyHex": update_signing_public_key(), "allowUnsignedDevelopment": allow_unsigned_update()},
    }


def bootstrap_core():
    """Install Core and create an unstarted IPC client plus identity seed.

    The caller owns the single start() + hello handshake. Keeping bootstrap free
    of process-start side effects makes lifecycle ownership explicit for both
    initial startup and restart paths.
    """
    paths.ensure_layout()
    core_path, core_hash, changed = core_installer.install_core(paths.core_path())
    core_installer.write_runtime_manifest(core_path, core_hash, changed)
    _smoke_metric(coreInstalledEpoch=time.time(), coreInstallChanged=bool(changed))
    seed = dpapi.load_or_create_identity_seed(paths.security_dir())
    client = CoreClient(
        core_path,
        paths.data_root(),
        paths.core_log_path(),
        app_version=app_version(),
        build_label=build_label(),
        release_revision=release_revision(),
        diagnostics=_DIAGNOSTICS,
        debug=_DEBUG_ENABLED,
    )
    return client, seed


def _smoke():
    global _SMOKE_LOG
    _SMOKE_LOG = os.path.join(paths.logs_dir(), "smoke-report.txt")
    os.makedirs(os.path.dirname(_SMOKE_LOG), exist_ok=True)
    open(_SMOKE_LOG, "w", encoding="utf-8").close()
    metrics = os.path.join(paths.logs_dir(), "smoke-metrics.json")
    try:
        os.remove(metrics)
    except OSError:
        pass
    _smoke_metric(shellStartedEpoch=_PROCESS_STARTED_EPOCH, smokeStartedEpoch=time.time())
    try:
        return _smoke_inner()
    except Exception:
        import traceback

        _p(traceback.format_exc())
        return 1


def _smoke_inner():
    # Exercise the GUI toolkit in the frozen artifact as well as Core IPC.
    # A console-only smoke cannot detect missing Tcl/Tk runtime data.
    import tkinter as tk

    toolkit = tk.Tk()
    try:
        toolkit.withdraw()
        toolkit.update_idletasks()
    finally:
        toolkit.destroy()
    _p("PSN %s M0 smoke" % release_version())
    if not single_instance.acquire_single_instance(paths.data_root()):
        _p("FAIL: second instance blocked mutex test env")
        return 1
    client, seed = bootstrap_core()
    if not seed or len(seed) != 64:
        _p("FAIL: bad identity seed")
        return 1
    _p("dataRoot:", paths.data_root())
    _p("corePath:", paths.core_path())
    try:
        import json as _json

        man_path = os.path.join(paths.runtime_dir(), "runtime-manifest.json")
        with open(man_path, encoding="utf-8") as fh:
            man = _json.load(fh)
        _p("coreInstall changed=%s hash=%s" % (man.get("changed"), man.get("coreSha256")))
    except OSError:
        _p("coreInstall manifest missing")
    events = []
    ready = threading.Event()

    def on_event(frame):
        events.append(frame)
        if frame.get("event") == "core.swarmReady":
            ready.set()

    client.start(on_event)
    _smoke_metric(coreSpawnedEpoch=time.time(), corePid=getattr(client.proc, "pid", None))
    try:
        ack = client.request("hello", hello_payload(seed), timeout=25)
        assert ack["ok"], ack
        assert ack["result"].get("coreProtocol") == 1, ack
        peer = ack["result"]["peerId"]
        _p("helloAck ok coreProtocol=%s peer=%s…" % (ack["result"].get("coreProtocol"), peer[:12]))
        r = client.request("getStatus", {}, timeout=10)
        assert r["ok"] and r["result"]["peerId"] == peer, r
        _p("getStatus ok swarm=%s" % r["result"].get("swarm"))
        _smoke_metric(helloAckEpoch=time.time(), readyEpoch=time.time(), corePid=getattr(client.proc, "pid", None))
        from runtime.updater import notify_update_ready

        notify_update_ready()
        # Give artifact-smoke a short, deterministic idle window to sample the
        # shell + Core working set before the 10k IPC stress begins.
        time.sleep(0.30)
        # 10000 framed request/event smoke messages without corruption
        n_ping = 10000
        for i in range(n_ping):
            pr = client.request("ping", {"seq": i}, timeout=30)
            assert pr["ok"] and pr["result"]["pong"] == i, pr
        _p("%d ping round-trips ok" % n_ping)
        deadline = time.time() + 25
        while time.time() < deadline and not ready.is_set():
            time.sleep(0.3)
            if events:
                for e in events:
                    if e.get("event") == "core.warning" and e["payload"].get("code") == "BOOTSTRAP_FAILED":
                        ready.set()
                        break
        st = client.request("getStatus", {}, timeout=10)["result"]
        _p("final swarm state:", st.get("swarm"))
        if st.get("swarm") not in ("booted", "booting"):
            # a BOOTSTRAP_FAILED in this sandbox network is tolerated for the
            # packaging gate; full DHT is validated in the E2E milestone.
            warn = [e for e in events if e.get("event") == "core.warning"]
            _p("note: swarm did not finish boot here; events:", [w["payload"]["code"] for w in warn])
    finally:
        client.stop(graceful=True)
        code = client.proc.poll()
        single_instance.release_single_instance()
    if code != 0:
        _p("FAIL: core exit code", code)
        return 1
    _smoke_metric(smokeCompleteEpoch=time.time(), smokePass=True)
    _p("M0 SMOKE PASS")
    return 0


def _gui():
    import tkinter as tk
    from tkinter import messagebox

    from gui.main_window import MainWindow
    from gui.i18n import t
    from windows.single_instance import acquire_single_instance, release_single_instance

    global _SMOKE_LOG
    if os.environ.get("PEERSYNC_GTRACE"):
        _SMOKE_LOG = os.path.join(paths.logs_dir(), "gui-trace.txt")
        open(_SMOKE_LOG, "w", encoding="utf-8").close()

    def gtrace(msg):
        if os.environ.get("PEERSYNC_GTRACE"):
            _p("[gui] " + msg)

    # Enable native crash diagnostics before any filesystem/Core bootstrap.
    # Startup failures are among the cases where the windowed build otherwise
    # has no console and therefore no useful user-visible signal.
    _enable_fault_log()

    def show_startup_error(exc):
        text = "Не удалось запустить PeerSync.\n\n%s" % exc
        error_root = None
        try:
            error_root = tk.Tk()
            error_root.withdraw()
            messagebox.showerror("PeerSync by Nickston", text, parent=error_root)
        except Exception:  # Tk itself may be the failing subsystem
            if os.name == "nt":
                try:
                    import ctypes

                    ctypes.windll.user32.MessageBoxW(None, text, "PeerSync by Nickston", 0x10)
                except Exception:
                    pass
        finally:
            if error_root is not None:
                try:
                    error_root.destroy()
                except Exception:
                    pass

    gate_acquired = False
    try:
        gtrace("acquire_single_instance...")
        gate_acquired = acquire_single_instance(paths.data_root())
        if not gate_acquired:
            gtrace("instance busy -> show running window")
            single_instance.signal_running_instance(paths.data_root())
            return 0
        gtrace("instance gate ok")
        client, seed = bootstrap_core()
    except Exception as exc:  # noqa: BLE001 - startup must fail visibly
        gtrace("startup bootstrap failed: %s" % exc)
        show_startup_error(exc)
        if gate_acquired:
            release_single_instance()
        return 1
    gtrace("core bootstrap ok")
    root = tk.Tk()
    root.withdraw()
    holder = {
        "client": client,
        "core_epoch": 0,
        "pending_clients": {},
        "pending_lock": threading.Lock(),
        "gate_released": False,
        "exiting": False,
        "stopping": False,
        "auto_restart_attempts": 0,
        "auto_restart_pending": False,
    }

    def track_pending_client(candidate):
        if candidate is None:
            return
        with holder["pending_lock"]:
            holder["pending_clients"][id(candidate)] = candidate

    def untrack_pending_client(candidate):
        if candidate is None:
            return
        with holder["pending_lock"]:
            holder["pending_clients"].pop(id(candidate), None)

    def pending_clients_snapshot():
        with holder["pending_lock"]:
            return list(holder["pending_clients"].values())

    from runtime.assets import ensure_icon

    icon_path = ensure_icon(paths.data_root())
    gtrace("tk ok icon=%s" % icon_path)

    def on_exit():
        if holder.get("exiting"):
            return
        gtrace("on_exit invoked")
        holder["exiting"] = True
        try:
            if win.tray:
                win.tray.destroy()
        except Exception:  # noqa: BLE001
            pass
        try:
            root.withdraw()
            root.update_idletasks()
        except Exception:  # noqa: BLE001
            pass

        def work():
            stop_errors = []
            try:
                holder["client"].stop(graceful=True, timeout=1.5)
            except Exception as exc:  # noqa: BLE001
                stop_errors.append("Core: %s" % exc)

            # Restart candidates are lifecycle-owned from bootstrap, not from
            # the later Tk apply callback. Exit may release the data-root gate
            # only after every candidate has crossed the same Job-empty fence.
            for pending in pending_clients_snapshot():
                try:
                    pending.stop(graceful=False)
                except Exception as exc:  # noqa: BLE001
                    stop_errors.append("candidate Core: %s" % exc)
                else:
                    untrack_pending_client(pending)

            if stop_errors:
                # Fail closed: keep the single-instance handle and the process
                # alive.  Releasing the gate here would allow a new shell/Core
                # to reuse the data-root while an old Job still has writers.
                def failed():
                    holder["exiting"] = False
                    try:
                        if root and root.winfo_exists():
                            root.deiconify()
                    except Exception:  # noqa: BLE001
                        pass
                    try:
                        messagebox.showerror(
                            "PeerSync by Nickston",
                            "Не удалось безопасно остановить Core. PeerSync не будет закрыт, "
                            "пока старое дерево процессов ещё может владеть файлами.\n\n"
                            + "\n".join(stop_errors),
                            parent=root,
                        )
                    except Exception:  # noqa: BLE001
                        pass

                win.post_ui(failed)
                return

            # The single-instance handles are Win32 resources, not Tk state.
            # Release them only after CoreClient proved every Job is empty.
            release_single_instance()
            holder["gate_released"] = True

            def done():
                try:
                    if root and root.winfo_exists():
                        root.destroy()
                except Exception:  # noqa: BLE001
                    pass

            win.post_ui(done)

        threading.Thread(target=work, name="core-stop", daemon=True).start()

    win = MainWindow(root, client, on_exit, app_version(), build_label(), icon_path=icon_path, release_revision=release_revision())
    gtrace("MainWindow ok tray=%s" % (win.tray is not None))

    def install_downloaded_update(result):
        # update.request already runs outside Tk while the payload is received,
        # but its completion callback is marshalled back to the UI thread. The
        # trust/hash verification and copy in launch_staged_update can scan a
        # large executable, so keep the entire install preparation off Tk.
        payload = dict(result or {})

        def work():
            try:
                from runtime.updater import comparable_app_version, is_newer_release, launch_staged_update, parse_release_revision

                staged = str(payload.get("path") or "")
                target_version = str(payload.get("version") or "")
                target_build = str(payload.get("buildLabel") or "")
                target_revision = parse_release_revision(payload.get("releaseRevision"))
                expected_size = payload.get("size")
                expected_sha256 = str(payload.get("sha256") or "")
                if payload.get("signatureRequired") is True and payload.get("signatureVerified") is not True:
                    raise RuntimeError("Подпись обновления обязательна, но не подтверждена")
                if payload.get("trustedSource") is not True:
                    raise RuntimeError("Источник обновления не отмечен как доверенное устройство")
                if not is_newer_release(
                    target_version,
                    target_build,
                    comparable_app_version(app_version(), build_label()),
                    build_label(),
                    target_revision,
                    release_revision(),
                ):
                    raise RuntimeError("Полученная версия не новее текущей")
                launch_staged_update(
                    staged,
                    expected_size,
                    expected_sha256,
                    app_version=target_version,
                    build_label=target_build,
                    platform=str(payload.get("platform") or ""),
                    signature=str(payload.get("signature") or ""),
                    public_key=update_signing_public_key(),
                    signature_required=payload.get("signatureRequired") is True,
                    release_revision=target_revision,
                )
            except Exception as exc:  # noqa: BLE001 - report installer failures to the UI
                win.post_ui(win.update_install_failed, exc)
                return

            # The updater helper waits for this process. Exit through the normal
            # lifecycle so Core/pipes/tray and the single-instance mutex are all
            # released before it replaces PSN.exe.
            win.post_ui(win.request_exit)

        threading.Thread(target=work, name="update-install", daemon=True).start()
        return True

    win.on_update_ready = install_downloaded_update

    def event_cb_for(owner):
        def event_cb(frame):
            if frame.get("event") != "core.stopped":
                win.post_event(frame, owner=owner)
                return

            def handle_stopped():
                if owner is not holder.get("client") or holder.get("exiting"):
                    return
                win._handle_event(frame)
                if holder.get("stopping"):
                    return
                win.set_restart_busy(True)
                win._set_status(t("core_restarting"), "warning")
                holder["auto_restart_pending"] = True
                started = restart_core(
                    automatic=True,
                    reason=(frame.get("payload") or {}).get("exitCode"),
                )
                if not started:
                    holder["auto_restart_pending"] = False
                    win.set_restart_busy(False)

            win.post_ui(handle_stopped)

        return event_cb

    holder["seed"] = seed
    restart_lock = threading.Lock()

    def restart_core(automatic=False, reason=None):
        # Acquire before creating the worker so two rapid UI invocations cannot
        # both observe the same live client and bootstrap competing cores.
        if holder.get("exiting") or not restart_lock.acquire(blocking=False):
            return False
        holder["stopping"] = True
        attempt = int(holder.get("auto_restart_attempts") or 0) if automatic else 0
        if not automatic:
            holder["auto_restart_attempts"] = 0

        # Invalidate every continuation captured by the currently published
        # Core before the restart worker can stop it. Tk cannot drain another
        # UI callback until on_restart() returns, so this is the lifecycle
        # publication boundary for async shell continuations.
        previous_epoch = holder["core_epoch"]
        restart_epoch = previous_epoch + 1
        holder["core_epoch"] = restart_epoch

        def release_restart():
            try:
                restart_lock.release()
            except RuntimeError:
                pass

        def work():
            candidate = None
            candidate_seed = None
            ack = None
            err = None
            try:
                old = holder["client"]
                # Do not bootstrap a replacement until the previous lifecycle
                # owner has synchronously completed its bounded stop sequence.
                old.stop(graceful=False)
                if holder.get("exiting"):
                    raise RuntimeError("application is exiting")

                candidate, candidate_seed = bootstrap_core()
                track_pending_client(candidate)
                if holder.get("exiting"):
                    raise RuntimeError("application is exiting")
                candidate.start(event_cb_for(candidate))
                if holder.get("exiting"):
                    raise RuntimeError("application is exiting")
                ack = candidate.request("hello", hello_payload(candidate_seed), timeout=25)
                if not ack or not ack.get("ok"):
                    code = ((ack or {}).get("error") or {}).get("code") or "START_FAILED"
                    raise RuntimeError(str(code))
                if ack.get("result", {}).get("coreProtocol") != 1:
                    raise RuntimeError("UNSUPPORTED protocol")
                if holder.get("exiting"):
                    raise RuntimeError("application is exiting")
            except Exception as exc:  # noqa: BLE001
                err = exc
                if candidate is not None:
                    try:
                        candidate.stop(graceful=False)
                    except Exception:  # noqa: BLE001
                        pass
                    untrack_pending_client(candidate)
                    candidate = None

            def apply():
                try:
                    if holder.get("exiting"):
                        holder["stopping"] = False
                        holder["auto_restart_pending"] = False
                        if candidate is not None:
                            try:
                                candidate.stop(graceful=False)
                            except Exception:  # noqa: BLE001
                                pass
                            finally:
                                untrack_pending_client(candidate)
                        return
                    if err is not None or candidate is None or candidate_seed is None:
                        holder["stopping"] = False
                        win._core_ready = False
                        win._invalidate_core_lifecycle(t("core_stopped"))
                        win._set_peers_offline()
                        next_attempt = attempt + 1
                        if automatic and next_attempt < CORE_RESTART_MAX_ATTEMPTS:
                            holder["auto_restart_attempts"] = next_attempt
                            holder["auto_restart_pending"] = False
                            delay = min(5.0, CORE_RESTART_BASE_DELAY * (2 ** attempt))
                            win.set_restart_busy(True)
                            win._set_status(t("core_restarting"), "warning")
                            root.after(delay, lambda: restart_core(automatic=True, reason=reason))
                        else:
                            holder["auto_restart_attempts"] = 0
                            holder["auto_restart_pending"] = False
                            detail = str(err or "START_FAILED")
                            win._set_status("Служба передачи остановлена: %s" % detail, "error")
                        return

                    # Publish only a fully started + hello-validated candidate.
                    # Until this point holder/win continue to reference the old
                    # (stopped) lifecycle owner, so a failed candidate can never
                     # escape and become an orphaned core.

                    untrack_pending_client(candidate)
                    holder["client"] = candidate
                    holder["seed"] = candidate_seed
                    if _DIAGNOSTIC_ENDPOINT is not None:
                        _DIAGNOSTIC_ENDPOINT.set_core_epoch(restart_epoch)
                    holder["auto_restart_attempts"] = 0
                    holder["auto_restart_pending"] = False

                    holder["stopping"] = False

                    win.core = candidate
                    win.on_core_ready()
                finally:
                    win.set_restart_busy(False)
                    release_restart()

            win.post_ui(apply)

        try:
            threading.Thread(target=work, name="core-restart", daemon=True).start()
        except Exception:
            # No restart work could have run, so preserve the initial owner's
            # epoch and allow its already queued continuations to remain valid.
            if holder.get("core_epoch") == restart_epoch:
                holder["core_epoch"] = previous_epoch
            holder["stopping"] = False
            holder["auto_restart_pending"] = False
            release_restart()
            raise
        return True

    win.on_restart = restart_core
    client.start(event_cb_for(client))
    gtrace("client started; hello...")

    initial_hello_owner = client
    initial_hello_epoch = holder["core_epoch"]

    def do_hello():
        def work():
            ack = None
            error = None
            try:
                ack = initial_hello_owner.request("hello", hello_payload(seed), timeout=25)
            except Exception as exc:  # noqa: BLE001 - worker must always report back to Tk
                error = str(exc) or exc.__class__.__name__

            def apply():
                # Initial hello is an async continuation owned by the initial
                # Core generation. A restart can stop that owner while this
                # request is still in flight; never let its late result mutate
                # the replacement generation's UI state.
                if (
                    holder.get("exiting")
                    or holder.get("core_epoch") != initial_hello_epoch
                    or holder.get("client") is not initial_hello_owner
                    or win.core is not initial_hello_owner
                ):
                    return
                if error is not None:
                    win._core_ready = False
                    win._set_status("Core error: %s" % error, "error")
                    win._update_controls()
                    return
                if not ack or not ack.get("ok"):
                    win._core_ready = False
                    code = ((ack or {}).get("error") or {}).get("code") or "START_FAILED"
                    win._set_status("Core error: %s" % code, "error")
                    win._update_controls()
                    return
                if ack.get("result", {}).get("coreProtocol") != 1:
                    win._core_ready = False
                    win._set_status("Core error: UNSUPPORTED protocol", "error")
                    win._update_controls()
                    return
                win.on_core_ready()
                from runtime.updater import notify_update_ready

                notify_update_ready()
                gtrace("hello done")

            win.post_ui(apply)

        threading.Thread(target=work, name="hello", daemon=True).start()

    root.after(0, do_hello)
    gtrace("entering mainloop")
    try:
        root.mainloop()
        gtrace("mainloop returned")
    finally:
        if not holder.get("gate_released"):
            # mainloop can return without the normal on_exit path (session
            # teardown, external root.destroy(), or an exception escaping Tk).
            # This safety net must obey the same ownership rule as on_exit:
            # NEVER release the data-root gate until every Core Job is proven
            # empty.  A bounded stop failure therefore keeps this process alive
            # and holding the lock while we retry the hard tree fence.  Checking
            # gate_released (not merely exiting) also covers an externally
            # destroyed Tk root while the normal exit worker is still running.
            remaining = [holder["client"]] + pending_clients_snapshot()
            while remaining:
                retry = []
                for owned_client in remaining:
                    try:
                        owned_client.stop(graceful=False)
                    except Exception as exc:  # noqa: BLE001
                        gtrace("fail-closed shutdown retry: %s" % exc)
                        retry.append(owned_client)
                    else:
                        if owned_client is not holder["client"]:
                            untrack_pending_client(owned_client)
                if not retry:
                    break
                remaining = retry
                time.sleep(0.25)
            release_single_instance()
            holder["gate_released"] = True
    return 0


def _probe():
    """Diagnostic mode built into the frozen EXE: examine _MEIPASS file access."""
    out_path = None
    try:
        base = paths.launcher_dir()
        os.makedirs(os.path.join(base, "data", "logs"), exist_ok=True)
        out_path = os.path.join(base, "data", "logs", "probe-report.txt")
    except Exception:  # noqa: BLE001
        out_path = os.path.join(HERE, "probe-report.txt")
    lines = []

    def note(s):
        lines.append(s)
        try:
            with open(out_path, "w", encoding="utf-8") as fh:
                fh.write("\n".join(lines) + "\n")
        except OSError:
            pass

    meipass = getattr(sys, "_MEIPASS", None)
    note("frozen=%s meipass=%s exe=%s" % (getattr(sys, "frozen", False), meipass, sys.executable))
    try:
        import tkinter as _tkr

        _r = _tkr.Tk()
        _r.withdraw()
        note("tkinter ok version=%s" % _tkr.TkVersion)
        _r.destroy()
    except Exception:  # noqa: BLE001
        import traceback

        note("tkinter FAIL: " + traceback.format_exc(limit=4))
    if not meipass:
        note("not a frozen build; probe meaningless")
        return 0
    note("listdir count=%d" % len(os.listdir(meipass)))
    samples = [n for n in ("core-manifest.json", "core-bundle.zip") if os.path.exists(os.path.join(meipass, n))]
    for name in samples:
        p = os.path.join(meipass, name)
        note("== %s size=%s" % (name, os.path.getsize(p)))
        try:
            os.stat(p)
            note("  stat ok")
        except OSError as exc:
            note("  stat fail %s winerror=%s" % (type(exc).__name__, getattr(exc, "winerror", None)))
        try:
            with open(p, "rb") as fh:
                fh.read(4)
            note("  open('rb') ok")
        except OSError as exc:
            note("  open fail %s winerror=%s strerror=%s" % (type(exc).__name__, getattr(exc, "winerror", None), exc.strerror))
        GENERIC_READ = 0x80000000
        FILE_SHARE_ALL = 0x7
        OPEN_EXISTING = 3
        k32 = ctypes.windll.kernel32
        h = k32.CreateFileW(p, GENERIC_READ, FILE_SHARE_ALL, None, OPEN_EXISTING, 0x80, None)
        if h in (-1, None):
            err = ctypes.GetLastError()
            note("  CreateFileW fail glerr=%d" % err)
        else:
            note("  CreateFileW ok (handle)")
            k32.CloseHandle(h)
        try:
            import subprocess

            r = subprocess.run(["icacls", p], capture_output=True, text=True, timeout=15)
            note("  icacls: " + (r.stdout or r.stderr).strip()[:400])
        except Exception as exc:  # noqa: BLE001
            note("  icacls failed: %s" % exc)

    # retry the failing one over time
    import time

    bad = samples[0] if samples else None
    if bad:
        p = os.path.join(meipass, bad)
        t0 = time.time()
        last_error = None
        while time.time() - t0 < 90:
            try:
                with open(p, "rb") as fh:
                    fh.read(4)
                note("retry ok after %.1fs" % (time.time() - t0))
                break
            except OSError as exc:
                last_error = exc
                time.sleep(3)
        else:
            note(
                "still failing after 90s: %s winerror=%s"
                % (type(last_error).__name__, getattr(last_error, "winerror", None))
            )
    note("probe done")
    return 0


def main():
    global _DEBUG_ENABLED, _DIAGNOSTICS, _DIAGNOSTIC_ENDPOINT
    if "--apply-update" in sys.argv:
        from runtime.updater import apply_update_cli

        return apply_update_cli(sys.argv)
    if "--recover-pending" in sys.argv:
        # Independent recovery of an unconfirmed update transaction. It runs from
        # the previous known-good launcher copy, so it must work even when the
        # freshly installed candidate cannot start at all.
        from runtime.updater import recover_pending_cli

        return recover_pending_cli(sys.argv)
    _DEBUG_ENABLED = "--debug" in sys.argv
    _install_crash_logging()
    try:
        paths.ensure_layout()
        try:
            from runtime.updater import reconcile_pending_update

            # Report the outcome of any update transaction left behind by a
            # killed helper or a power loss. Only the durable record is settled
            # here; file replacement is owned by the independent recovery helper.
            reconciled = reconcile_pending_update()
            if reconciled:
                _p("update reconcile:", reconciled)
        except Exception as exc:  # noqa: BLE001 - recovery bookkeeping never blocks startup
            _p("note: update reconcile failed:", exc)
        _DIAGNOSTICS = DiagnosticsRecorder(
            paths.logs_dir(),
            debug=_DEBUG_ENABLED,
            legacy_core_path=paths.core_log_path(),
            app_info={"version": app_version(), "buildLabel": build_label(), "releaseRevision": release_revision()},
        )
        _DIAGNOSTICS.log("info", "shell", "lifecycle", "shell.start", "PeerSync shell starting")
        # The live diagnostics endpoint is debug-only on purpose. A release build
        # must not publish a live diagnostic surface; external clients read the
        # bounded offline logs instead. --debug opens the private, token-gated
        # named pipe for local troubleshooting.
        if _DEBUG_ENABLED:
            _DIAGNOSTIC_ENDPOINT = DiagnosticsEndpoint(paths.data_root(), _DIAGNOSTICS)
            _DIAGNOSTIC_ENDPOINT.start()
            _DIAGNOSTICS.log("info", "shell", "diagnostics", "endpoint.started", "Diagnostics endpoint started")
        try:
            if "--probe" in sys.argv:
                return _probe()
            if "--smoke" in sys.argv:
                return _smoke()
            return _gui()
        finally:
            if _DIAGNOSTIC_ENDPOINT is not None:
                _DIAGNOSTIC_ENDPOINT.stop()
                _DIAGNOSTIC_ENDPOINT = None
            if _DIAGNOSTICS is not None:
                _DIAGNOSTICS.log("info", "shell", "lifecycle", "shell.stop", "PeerSync shell stopping")
                _DIAGNOSTICS.close()
                _DIAGNOSTICS = None
    except Exception:
        if _DIAGNOSTIC_ENDPOINT is not None:
            try:
                _DIAGNOSTIC_ENDPOINT.stop()
            except Exception:
                pass
            _DIAGNOSTIC_ENDPOINT = None
        if _DIAGNOSTICS is not None:
            try:
                _DIAGNOSTICS.log("critical", "shell", "lifecycle", "shell.fatal", "PeerSync shell failed")
                _DIAGNOSTICS.close()
            except Exception:
                pass
            _DIAGNOSTICS = None
        raise


def _install_crash_logging():
    launch_error_path = os.path.join(paths.logs_dir(), "launch-error.txt")
    try:
        os.makedirs(paths.logs_dir(), exist_ok=True)
        paths.rotate_log_files(launch_error_path, max_bytes=1024 * 1024, backups=3)
    except OSError:
        pass

    def dump(kind):
        def hook(*args):
            try:
                import traceback

                if _DIAGNOSTICS is not None:
                    _DIAGNOSTICS.log("critical", "shell", "crash", "process.exception", kind)
                os.makedirs(paths.logs_dir(), exist_ok=True)
                # Exception storms must not turn the portable data directory into
                # an unbounded append-only sink. Rotate both at startup and before
                # appending a fresh crash record.
                paths.rotate_log_files(launch_error_path, max_bytes=1024 * 1024, backups=3)
                with open(launch_error_path, "a", encoding="utf-8") as fh:
                    fh.write("[%s] %s\n" % (kind, time.strftime("%Y-%m-%d %H:%M:%S")))
                    if kind == "excepthook":
                        fh.write("".join(traceback.format_exception(*args)))
                    else:
                        fh.write(repr(args) + "\n")
            except OSError:
                pass
        return hook

    sys.excepthook = dump("excepthook")
    try:
        import threading

        threading.excepthook = lambda s: dump("thread")((s.exc_type, s.exc_value, s.exc_traceback))
    except Exception:  # noqa: BLE001
        pass


import ctypes  # noqa: E402


if __name__ == "__main__":
    raise SystemExit(main())
