"""Generate apps/portable-python/core_payload.py embedding the built core EXE.

Rationale: PyInstaller onefile on Windows 6.22 exposes
added data files as zero-byte/ACCESS_DENIED deferred placeholders in _MEIPASS
at runtime on this machine, so a raw `open()` of an embedded PSNCore
payload fails. The PYZ module graph loads fine, so we embed the core bytes and
the app icon as module constants:
- no PSNCore.exe ever lands in %TEMP% (firewall/AV discipline),
- the installer streams it straight to stable data/runtime/PSNCore.exe.
"""

import hashlib
import pathlib
import sys

src = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "build/core/PSNCore.exe")
ico = pathlib.Path("apps/portable-python/assets/peersync.ico")
wordmark_paths = {
    "peersync-wordmark-light.png": pathlib.Path(
        "apps/portable-python/assets/peersync-wordmark-light.png"
    ),
    "peersync-wordmark-dark.png": pathlib.Path(
        "apps/portable-python/assets/peersync-wordmark-dark.png"
    ),
}
out = pathlib.Path("apps/portable-python/core_payload.py")
data = src.read_bytes()
digest = hashlib.sha256(data).hexdigest()
ico_bytes = ico.read_bytes() if ico.is_file() else b""
wordmark_bytes = {
    name: path.read_bytes() if path.is_file() else b""
    for name, path in wordmark_paths.items()
}
if not ico_bytes or not all(wordmark_bytes.values()):
    try:
        sys.path.insert(0, str(pathlib.Path("apps/portable-python").resolve()))
        import core_payload as prev  # noqa: E402

        if not ico_bytes:
            ico_bytes = getattr(prev, "ICO", b"") or b""
        previous_wordmarks = getattr(prev, "WORDMARKS", {}) or {}
        for name in wordmark_bytes:
            if not wordmark_bytes[name]:
                wordmark_bytes[name] = previous_wordmarks.get(name, b"")
    except Exception:
        pass
if ico_bytes and not ico.is_file():
    ico.parent.mkdir(parents=True, exist_ok=True)
    ico.write_bytes(ico_bytes)
out.write_text(
    "# generated by scripts/gen-core-payload.py — do not edit, do not commit\n"
    "CORE_SHA256 = %r\n"
    "CORE_SIZE = %d\n"
    "CORE = %r\n"
    "ICO_NAME = 'peersync.ico'\n"
    "ICO = %r\n"
    "WORDMARKS = %r\n" % (digest, len(data), data, ico_bytes, wordmark_bytes),
    encoding="utf-8",
)
print(
    "payload module:",
    out,
    len(data),
    "bytes core embedded, sha",
    digest,
    "+ ico",
    len(ico_bytes),
    "+ wordmarks",
    sum(len(value) for value in wordmark_bytes.values()),
)
