"""Fingerprint the product source tree that produced a build.

The fingerprint is a SHA-256 over ``relativePath + NUL + fileSha256 + LF`` for
every source file that can influence the produced binaries, sorted by the POSIX
relative path. Generated output, dependencies, archives and logs are excluded so
the value depends on source only.

The same file set is used by ``check-build-reproducibility.py``; the exclusion
rules are defined once, here, so a reproducibility run and a release manifest
cannot disagree about what "the source" means.
"""

import argparse
import hashlib
import json
import os
import subprocess
import sys

# Generated by the build, never part of the source identity.
GENERATED_FILES = frozenset({
    "build-report.json",
    "apps/portable-python/core_payload.py",
    "apps/portable-python/build_info.py",
})

# Binary/archive/log payloads that are never product source. Images are *not*
# excluded: the .ico and .png assets are inputs to the Core build and the frozen
# launcher, so they belong to the source identity and to the reproducibility
# export.
EXCLUDED_SUFFIXES = frozenset({
    ".pyc", ".pyo", ".log", ".zip", ".7z", ".rar", ".tar", ".gz", ".tgz",
    ".bz2", ".xz", ".exe", ".dll", ".pdb",
})
EXCLUDED_PARTS = frozenset({
    # Tool caches and build output: present in some checkouts and not in others
    # (a linter cache in one CI job, a downloaded artifact in another), so they
    # must never become part of the identity a release is verified against.
    "__pycache__", "node_modules", ".git", "dist", "build", "out", ".tmp",
    ".ruff_cache", ".pytest_cache", ".mypy_cache", ".cache", "coverage",
    ".venv", "venv", "release-artifact",
})

_HASH_CHUNK = 1024 * 1024


def file_sha256(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        while True:
            block = handle.read(_HASH_CHUNK)
            if not block:
                break
            digest.update(block)
    return digest.hexdigest()


def _git_listed_names(root):
    # An export nested below build/ belongs to its parent repository, but Git
    # lists no source files there. Fingerprint the export through the filesystem.
    if not os.path.exists(os.path.join(root, ".git")):
        return None
    try:
        raw = subprocess.check_output(
            ["git", "ls-files", "-z", "--cached", "--others", "--exclude-standard"],
            cwd=root, stderr=subprocess.DEVNULL,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return [name for name in raw.decode("utf-8").split("\0") if name]


def _walked_names(root):
    names = []
    for current, directories, files in os.walk(root):
        directories[:] = [name for name in directories if name not in EXCLUDED_PARTS]
        for name in files:
            full = os.path.join(current, name)
            names.append(os.path.relpath(full, root).replace(os.sep, "/"))
    return names


def source_file_names(root):
    """Relative POSIX paths of every file that participates in the fingerprint."""
    names = _git_listed_names(root)
    if names is None:
        names = _walked_names(root)
    selected = []
    for name in names:
        normalized = name.replace(os.sep, "/")
        # Only a literal "./" prefix is stripped: a leading dot is meaningful
        # (.github/workflows must stay in the source identity).
        while normalized.startswith("./"):
            normalized = normalized[2:]
        if not normalized or normalized in GENERATED_FILES:
            continue
        parts = set(normalized.split("/"))
        if parts & EXCLUDED_PARTS:
            continue
        if os.path.splitext(normalized)[1].lower() in EXCLUDED_SUFFIXES:
            continue
        absolute = os.path.join(root, normalized.replace("/", os.sep))
        if not os.path.isfile(absolute):
            continue
        selected.append(normalized)
    return sorted(set(selected))


def source_fingerprint(root):
    """SHA-256 over ``relativePath + NUL + fileSha256 + LF`` in path order."""
    names = source_file_names(root)
    digest = hashlib.sha256()
    for name in names:
        digest.update(name.encode("utf-8"))
        digest.update(b"\0")
        digest.update(file_sha256(os.path.join(root, name.replace("/", os.sep))).encode("ascii"))
        digest.update(b"\n")
    return digest.hexdigest(), len(names)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir)))
    parser.add_argument("--json", action="store_true", help="print the fingerprint as JSON")
    args = parser.parse_args(argv)
    fingerprint, count = source_fingerprint(args.root)
    if args.json:
        print(json.dumps({"sourceFingerprint": fingerprint, "sourceFiles": count}, sort_keys=True))
    else:
        print(fingerprint)
    return 0


if __name__ == "__main__":
    sys.exit(main())
